notifications: 
    email:
      recipients:
        - soyturk.huseyin61@gmail.com

      on_success: always
      on_failure: always  
language: node_js
node_js:
    - 12
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
    - export PATH="$HOME/.yarn/bin:$PATH"
script:
    - yarn build
    - yarn test
deploy:
    provider: npm
    email: "soyturk.huseyin61@gmail.com"
    api_key: "491b5faf-59cc-4a0c-bc94-50dd7b6b1429"
cache: 
    yarn: true
