notifications: 
    email:
      recipients:
        - soyturk.huseyin61@gmail.com

      on_success: always
      on_failure: always  
language: node_js
node_js:
    - 10
    - 11
    - 12
scripts:
    - npm run test
    - codecov -f coverage/*.json
cache: 
    npm: true
